.TH CMAKEFBC 1 "2016-11-24" "FreeBASIC wrapper script for CMake"
.SH NAME
cmakefbc \- FreeBASIC wrapper script for CMake
.SH DESCRIPTION
Calls cmake with CMAKE_MODULE_PATH set to FreeBASIC extension scripts. Use it to configure your build tree (instead of 'cmake').
.SH SYNOPSIS
.B cmakefbc \fR[\fIcmake-options\fR]

.SH OPTIONS
.TP
.I cmake-options\fR
Any option understood by CMake command line.
.SH "SEE ALSO"
A detailed documentation is available in html format at
.B
http://users.freebasic-portal.de/tjf/Projekte/cmakefbc/doc/html/
.SH COPYRIGHT
Copyright \(co 2014\-2016 Thomas{ doT ]Freiherr[ At ]gmx[ DoT }net
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License GPLv3 <http://www.gnu.org/licenses/gpl-3.0.html>.
There is NO WARRANTY, to the extent permitted by law.
.SH BUGS
Any bugs should be reported on the github tracker located at https://github.com/DTJF/cmakefbc

.SH AUTHOR
This manpage written by Thomas Freiherr (https://github.com/DTJF/cmakefbc)
